# This file was generated by GoReleaser. DO NOT EDIT.
class Humanlog < Formula
  desc ""
  homepage ""
  version "0.3.7"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/casualjim/humanlog/releases/download/v0.3.7/humanlog_0.3.7_darwin_amd64.tar.gz"
    sha256 "e6e82292d4f0f97ed3a2df531e72b94a22a3b182e69b9d3ccd6283350060c581"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/casualjim/humanlog/releases/download/v0.3.7/humanlog_0.3.7_linux_amd64.tar.gz"
      sha256 "0daa8a36efc871e6a5ba8159f5bf664b0449a868b11ead7ba2d9ecbea28e0fc7"
    end
  end

  def install
    bin.install "humanlog"
  end
end
